import { readFileSync } from 'node:fs'

// Bundled server-owned v2.4.1 styles do not depend on the client module booting.
const dialogStyles = readFileSync(new URL('./login-dialog.css', import.meta.url), 'utf8')
const androidStyles = readFileSync(new URL('./login-android.css', import.meta.url), 'utf8')

export function renderLoginPage(nonce, stylesheetUrl = '') {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>登录 · DeepSeek Harness</title><style nonce="${nonce}">
:root{color-scheme:light dark;--dsw-alias-bg-base:#fff;--dsw-alias-bg-layer-2:#fff;--dsw-alias-border-inverted:#ffffff80;--dsw-alias-border-l2:#e4e6eb;--dsw-alias-label-primary:#0f1115;--dsw-alias-label-secondary:#62656d;--dsw-alias-label-tertiary:#8b8e96;--dsw-alias-label-primary-foreground:#fff;--dsw-alias-button-primary-fill:#4169e1;--dsw-alias-button-primary-hover:#3458c8;--dsw-alias-interactive-bg-hover:#f2f3f5;--dsw-alias-brand-primary:#4169e1;--dsw-alias-state-error-primary:#d54941;--dsw-shadow-lv3:0 16px 48px #0000001f}
@media(prefers-color-scheme:dark){:root{--dsw-alias-bg-base:#202124;--dsw-alias-bg-layer-2:#292a2e;--dsw-alias-border-inverted:#ffffff14;--dsw-alias-border-l2:#414349;--dsw-alias-label-primary:#eceef3;--dsw-alias-label-secondary:#b0b3bb;--dsw-alias-label-tertiary:#868b96;--dsw-alias-interactive-bg-hover:#34363b;--dsw-alias-state-error-primary:#ff827c}}
body{margin:0;background:var(--dsw-alias-bg-base)}[hidden]{display:none!important}${dialogStyles}
[data-lha-overlay]{box-sizing:border-box;overflow:auto}[data-lha-dialog]{flex-shrink:0;margin:auto}[data-lha-content] [data-lha-body]{padding:0}[data-lha-content] [data-lha-footer]{padding:0}[data-lha-body] p{margin:0}#confirmField{margin-top:16px}#setupHint{margin-top:12px}#form [data-lha-footer]{margin-top:16px}#passkeyPanel [data-lha-desc]{margin-top:0}
${androidStyles}</style>${stylesheetUrl ? `<link rel="stylesheet" href="${stylesheetUrl}">` : ''}</head><body class="han-login" data-checking><main data-lha-overlay><div data-lha-mask></div><section data-lha-dialog aria-labelledby="title"><div data-lha-content>
<p data-lha-wordmark>dsh android</p><h2 data-lha-title id="title">登录</h2><p data-lha-desc id="description">输入访问密码以继续使用 DSH。</p>
<div data-lha-body><p data-lha-hint id="passkeyHint" hidden></p><div data-lha-error id="error" role="alert" hidden></div>
<div data-lha-tabs id="tabs" hidden><button type="button" id="passkeyTab">Passkey</button><button type="button" id="passwordTab">密码</button></div>
<div id="passkeyPanel" hidden><p data-lha-desc>使用本机指纹、面容或安全密钥登录。</p><button type="button" data-lha-btn class="passkey" id="passkeyButton">使用 Passkey 登录</button></div>
<div data-lha-server><label data-lha-field><span>IP / 域名</span><input id="serverHost" type="text" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="服务器 IP 或域名"></label><label data-lha-field><span>端口</span><input id="serverPort" type="text" inputmode="numeric" autocomplete="off" aria-label="服务器端口"></label></div>
<form id="form" class="han-login-form"><label data-lha-field><span>密码</span><input id="password" type="password" autocomplete="current-password" required placeholder="请输入访问密码"></label><label data-lha-field id="confirmField" hidden><span>确认密码</span><input id="confirm" type="password" autocomplete="new-password" placeholder="再次输入"></label><p data-lha-hint id="setupHint" hidden>密码至少 8 位</p><div data-lha-footer><button type="submit" data-lha-btn class="primary" id="submit" disabled>继续</button></div></form>
<p data-lha-hint id="status" role="status" aria-live="polite">正在检查访问控制…</p><button type="button" data-lha-btn id="cancel" hidden>取消</button></div></div></section></main>
<script nonce="${nonce}">
const $=id=>document.getElementById(id),api='/dsh-local-hanaccount/api';let setup=false,ready=false,busy=false,pageLive=true,pageEpoch=0,controller;
$('serverHost').value=location.hostname;$('serverPort').value=location.port||(location.protocol==='https:'?'443':'80');
function serverUrl(){const host=$('serverHost').value.trim(),port=$('serverPort').value.trim();if(!host||/[\\\\/?#@\\s]/.test(host)||!/^\\d+$/.test(port)||Number(port)<1||Number(port)>65535)throw Error('请输入有效的 IP / 域名和端口（1–65535）。');if(host===location.hostname&&Number(port)===Number(location.port||(location.protocol==='https:'?443:80)))return location.origin+'/';const bracketed=host.includes(':')&&!host.startsWith('[')?'['+host+']':host;const url=new URL('https://'+bracketed+':'+port+'/');if(url.username||url.password||url.search||url.hash)throw Error('服务器地址无效。');return url.href}
function changeServer(){if(busy)return;try{const url=serverUrl();$('password').value='';$('confirm').value='';update();if(new URL(url).origin===location.origin)return;if(window.HanApp&&typeof HanApp.postMessage==='function'){HanApp.postMessage(JSON.stringify({version:1,id:'site-change',type:'changeWebsite',payload:{url}}));$('status').textContent='请确认切换服务器。'}else if(confirm('切换到 '+url+'？请在目标服务器重新输入密码。'))location.assign(url)}catch(error){$('error').textContent=error.message;$('error').hidden=false}}
let platformSequence=0;const platformPending=new Map();let platformBridge,platformPrevious,platformReceive;
function restorePlatform(){if(platformPending.size||!platformBridge)return;if(platformBridge.onmessage===platformReceive)platformBridge.onmessage=platformPrevious;platformBridge=platformPrevious=platformReceive=undefined}
function platform(type,payload={}){if(!pageLive)return Promise.reject(Error('page_closed'));const bridge=window.HanApp;if(!bridge||typeof bridge.postMessage!=='function'||platformPending.size>=4)return Promise.reject(Error('platform_unavailable'));if(!platformBridge){platformBridge=bridge;platformPrevious=bridge.onmessage;platformReceive=event=>{let value;try{value=JSON.parse(event.data)}catch{return}const pending=value.version===1&&platformPending.get(value.id);if(!pending){if(typeof platformPrevious==='function')platformPrevious(event);return}clearTimeout(pending.timer);clearTimeout(pending.retry);platformPending.delete(value.id);restorePlatform();value.ok===true?pending.resolve(value.result||{}):pending.reject(Error(value.error||'platform_unavailable'))};bridge.onmessage=platformReceive}if(platformBridge!==bridge)return Promise.reject(Error('platform_unavailable'));return new Promise((resolve,reject)=>{const id='login-'+(++platformSequence);const timer=setTimeout(()=>{clearTimeout(platformPending.get(id)?.retry);platformPending.delete(id);restorePlatform();reject(Error('platform_timeout'))},1500);platformPending.set(id,{resolve,reject,timer});try{const raw=JSON.stringify({version:1,id,type,payload});if(raw.length>16384)throw Error('platform_message_too_large');bridge.postMessage(raw);if(type==='capabilities'&&platformPending.has(id)){const retry=()=>{const pending=platformPending.get(id);if(!pending||!pageLive)return;try{bridge.postMessage(raw)}catch{}if(platformPending.has(id))pending.retry=setTimeout(retry,200)};platformPending.get(id).retry=setTimeout(retry,200)}}catch(error){clearTimeout(timer);platformPending.delete(id);restorePlatform();reject(error)}})}
window.addEventListener?.('pagehide',()=>{pageLive=false;pageEpoch++;controller?.abort();for(const pending of platformPending.values()){clearTimeout(pending.timer);clearTimeout(pending.retry);pending.reject(Error('page_closed'))}platformPending.clear();restorePlatform()});
window.addEventListener?.('pageshow',()=>{const returning=!pageLive;pageLive=true;if(returning){revealLogin();if(!ready)checkAccess()}});

async function saveCredential(password){if(typeof password!=='string'||!password||password.length>4096)return;const caps=await platform('capabilities');if(caps.credentialStorage!==true)return;await platform('saveCredential',{password})}
let surfaceReadySent=false;function notifySurfaceReady(){if(surfaceReadySent)return;surfaceReadySent=true;try{window.HanApp?.postMessage(JSON.stringify({version:1,id:'login-ready',type:'pageReady',payload:{}}))}catch{}}
function revealLogin(){document.body?.removeAttribute('data-checking');notifySurfaceReady()}
let restoring=false;async function restoreCredential(automatic=false){let entered=false;try{if(automatic&&window.localStorage?.getItem('lha-auto-login-disabled')==='1'){revealLogin();return}}catch{}if(restoring||setup||busy||$('password').value){if(automatic)revealLogin();return}const epoch=pageEpoch;let origin;try{origin=new URL(serverUrl()).origin;if(origin!==location.origin){if(automatic)revealLogin();return}}catch{if(automatic)revealLogin();return}restoring=true;if(automatic)$('status').textContent='正在检查设备缓存…';try{const caps=await platform('capabilities');if(caps.credentialStorage!==true)return;const saved=await platform('readCredential');if(pageLive&&epoch===pageEpoch&&!busy&&!setup&&!$('password').value&&new URL(serverUrl()).origin===origin&&typeof saved.password==='string'&&saved.password.length>0&&saved.password.length<=4096){$('password').value=saved.password;update();if(automatic)entered=await run(signal=>request('/auth/login',{password:saved.password},signal));}}catch{}finally{restoring=false;if(automatic&&!entered&&pageLive){$('status').textContent='';revealLogin()}}}

$('password').onfocus=()=>restoreCredential();
const messages={invalid_password:'密码不正确，请重试。',access_denied:'当前访问被拒绝，请检查访问规则。',proxy_misconfigured:'反向代理配置错误，请联系管理员。',native_bridge_unavailable:'服务器认证暂不可用，请联系管理员。',password_not_configured:'请先在服务器本机设置访问密码。'};
async function request(path,body,signal){const timeout=new AbortController();const timer=setTimeout(()=>timeout.abort(),8000);const onAbort=()=>timeout.abort();if(signal){if(signal.aborted)timeout.abort();else signal.addEventListener('abort',onAbort)}try{const r=await fetch(api+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:timeout.signal,redirect:'error'});const j=await r.json();if(!r.ok)throw Error(j.code==='rate_limited'?'尝试过多，请在 '+(j.retryAfterSec||60)+' 秒后重试。':messages[j.code]||'操作失败，请重试。');return j}finally{clearTimeout(timer);signal?.removeEventListener('abort',onAbort)}}
function update(){$('serverHost').disabled=$('serverPort').disabled=busy;let matches=false,valid=false;try{matches=new URL(serverUrl()).origin===location.origin;valid=true}catch{}$('password').disabled=$('confirm').disabled=!matches||busy;$('passkeyButton').disabled=$('passkeyTab').disabled=!matches||busy;if(!matches)mode(false);$('submit').disabled=!valid||!ready||busy||(matches&&(!$('password').value||(setup&&($('password').value.length<8||$('password').value!==$('confirm').value))));}
$('serverHost').oninput=$('serverPort').oninput=()=>{$('password').value='';$('confirm').value='';update()};
function mode(passkey){try{if(new URL(serverUrl()).origin!==location.origin)passkey=false}catch{passkey=false}$('passkeyPanel').hidden=!passkey;$('form').hidden=passkey;$('passkeyTab').classList.toggle('active',passkey);$('passwordTab').classList.toggle('active',!passkey)}
async function run(action,rememberPassword=false){if(busy||!pageLive)return;const button=$('form').hidden?$('passkeyButton'):$('submit'),label=button.textContent;busy=true;controller=new AbortController;const signal=controller.signal;$('error').hidden=true;$('cancel').hidden=true;button.textContent='登录中…';$('status').textContent=document.body?.hasAttribute('data-checking')?'登录中…':'';$('passkeyButton').disabled=true;update();try{await action(signal);if(pageLive&&!signal.aborted){if(rememberPassword){try{await saveCredential($('password').value)}catch{}}if(!pageLive||signal.aborted)return;try{window.localStorage?.removeItem('lha-auto-login-disabled')}catch{}$('password').value='';$('confirm').value='';location.replace('/');return true}}catch(e){if(e.name==='AbortError')$('status').textContent='已取消';else{$('error').textContent=e.message;$('error').hidden=false;$('status').textContent=''}}finally{busy=false;controller=null;button.textContent=label;$('cancel').hidden=true;$('passkeyButton').disabled=false;update()}}
$('cancel').onclick=()=>controller?.abort();$('password').oninput=$('confirm').oninput=update;$('passwordTab').onclick=()=>mode(false);$('passkeyTab').onclick=()=>mode(true);
$('form').onsubmit=e=>{e.preventDefault();if($('submit').disabled)return;if(new URL(serverUrl()).origin!==location.origin){changeServer();return}run(signal=>request(setup?'/auth/setup':'/auth/login',{password:$('password').value},signal),true)};
function buffer(value){const text=atob(value.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(text,c=>c.charCodeAt(0)).buffer}
function encoded(value){return btoa(String.fromCharCode(...new Uint8Array(value))).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'')}
$('passkeyButton').onclick=()=>{try{if(new URL(serverUrl()).origin!==location.origin||$('passkeyButton').disabled)return}catch{return}return run(async signal=>{const options=await request('/auth/passkey/login/options',{},signal);options.challenge=buffer(options.challenge);options.allowCredentials=(options.allowCredentials||[]).map(c=>({...c,id:buffer(c.id)}));const cred=await navigator.credentials.get({publicKey:options,signal});if(!cred)throw Error('已取消 Passkey 登录');const response=cred.response;await request('/auth/passkey/login/verify',{id:cred.id,rawId:encoded(cred.rawId),type:cred.type,response:{clientDataJSON:encoded(response.clientDataJSON),authenticatorData:encoded(response.authenticatorData),signature:encoded(response.signature),...(response.userHandle?{userHandle:encoded(response.userHandle)}:{})},clientExtensionResults:cred.getClientExtensionResults?.()||{}},signal)})};
function checkAccess(attempt=0){const checkingEpoch=pageEpoch;request('/auth/me').then(me=>{if(!pageLive||checkingEpoch!==pageEpoch)return;if(me.authenticated&&me.nativeAuthenticated){location.replace('/');return}setup=!me.passwordConfigured;$('title').textContent=setup?'设置访问密码':'登录';$('description').textContent=setup?'首次使用需为本机 DSH 设置访问密码，用于保护 Web 界面与插件 API。':'输入访问密码以继续使用 DSH。';$('confirmField').hidden=$('setupHint').hidden=!setup;$('confirm').required=setup;if(setup){$('password').minLength=8;$('password').autocomplete='new-password';$('password').placeholder='至少 8 位';$('submit').textContent='设置密码并继续';document.querySelector('[data-lha-dialog]').setAttribute('data-lha-setup','')}const passkey=me.passkey||{},canPasskey=isSecureContext&&typeof PublicKeyCredential!=='undefined'&&passkey.available;if(!setup&&canPasskey&&passkey.count>0){$('tabs').hidden=false;mode(false)}else if(!canPasskey&&passkey.hint){$('passkeyHint').textContent=passkey.hint;$('passkeyHint').hidden=false}ready=true;$('status').textContent='';update();if(!setup){notifySurfaceReady();restoreCredential(true)}else revealLogin()}).catch(error=>{if(!pageLive||checkingEpoch!==pageEpoch)return;if(attempt<2&&error?.name!=='AbortError'){setTimeout(()=>{if(pageLive&&checkingEpoch===pageEpoch)checkAccess(attempt+1)},400*(attempt+1));return}revealLogin();$('error').textContent='连接暂不可用，请稍后重试。';$('error').hidden=false;$('status').textContent=''})}
checkAccess();
</script></body></html>`
}
