import { readFileSync } from 'node:fs'

// Keep the previous access-control dialog's styles as the single visual source.
const clientSource = readFileSync(new URL('../client.js', import.meta.url), 'utf8')
const start = clientSource.indexOf('[data-lha-overlay]{')
const end = clientSource.indexOf('.dsh-lha-root{', start)
if (start < 0 || end < 0) throw new Error('Access-control dialog styles unavailable')
const dialogStyles = clientSource.slice(start, end)

export function renderLoginPage(nonce) {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>登录 · DeepSeek Harness</title><style nonce="${nonce}">
:root{color-scheme:light dark;--dsw-alias-bg-base:#fff;--dsw-alias-bg-layer-2:#fff;--dsw-alias-border-inverted:#ffffff80;--dsw-alias-border-l2:#e4e6eb;--dsw-alias-label-primary:#0f1115;--dsw-alias-label-secondary:#62656d;--dsw-alias-label-tertiary:#8b8e96;--dsw-alias-label-primary-foreground:#fff;--dsw-alias-button-primary-fill:#4169e1;--dsw-alias-button-primary-hover:#3458c8;--dsw-alias-interactive-bg-hover:#f2f3f5;--dsw-alias-brand-primary:#4169e1;--dsw-alias-state-error-primary:#d54941;--dsw-shadow-lv3:0 16px 48px #0000001f}
@media(prefers-color-scheme:dark){:root{--dsw-alias-bg-base:#202124;--dsw-alias-bg-layer-2:#292a2e;--dsw-alias-border-inverted:#ffffff14;--dsw-alias-border-l2:#414349;--dsw-alias-label-primary:#eceef3;--dsw-alias-label-secondary:#b0b3bb;--dsw-alias-label-tertiary:#868b96;--dsw-alias-interactive-bg-hover:#34363b;--dsw-alias-state-error-primary:#ff827c}}
body{margin:0;background:var(--dsw-alias-bg-base)}[hidden]{display:none!important}${dialogStyles}
[data-lha-overlay]{box-sizing:border-box;overflow:auto}[data-lha-dialog]{flex-shrink:0;margin:auto}[data-lha-content] [data-lha-body]{padding:0}[data-lha-content] [data-lha-footer]{padding:0}[data-lha-body] p{margin:0}#confirmField{margin-top:16px}#setupHint{margin-top:12px}#form [data-lha-footer]{margin-top:16px}#passkeyPanel [data-lha-desc]{margin-top:0}
</style></head><body><main data-lha-overlay><div data-lha-mask></div><section data-lha-dialog role="dialog" aria-modal="true" aria-labelledby="title"><div data-lha-content>
<p data-lha-wordmark>DEEPSEEK HARNESS</p><h2 data-lha-title id="title">登录</h2><p data-lha-desc id="description">输入访问密码以继续使用 DSH。</p>
<div data-lha-body><p data-lha-hint id="ip" hidden></p><div data-lha-warn id="warning" hidden>您的 IP 不在白名单，登录后请在设置中添加。</div><p data-lha-hint id="passkeyHint" hidden></p><div data-lha-error id="error" role="alert" hidden></div>
<div data-lha-tabs id="tabs" hidden><button type="button" id="passkeyTab">Passkey</button><button type="button" id="passwordTab">密码</button></div>
<div id="passkeyPanel" hidden><p data-lha-desc>使用本机指纹、面容或安全密钥登录。</p><button type="button" data-lha-btn class="passkey" id="passkeyButton">使用 Passkey 登录</button></div>
<form id="form"><label data-lha-field><span>密码</span><input id="password" type="password" autocomplete="current-password" required autofocus></label><label data-lha-field id="confirmField" hidden><span>确认密码</span><input id="confirm" type="password" autocomplete="new-password" placeholder="再次输入"></label><p data-lha-hint id="setupHint" hidden>密码至少 8 位</p><div data-lha-footer><button type="submit" data-lha-btn class="primary" id="submit" disabled>继续</button></div></form>
<p data-lha-hint id="status" role="status" aria-live="polite">正在检查访问控制…</p><button type="button" data-lha-btn id="cancel" hidden>取消</button></div></div></section></main>
<script nonce="${nonce}">
const $=id=>document.getElementById(id),api='/dsh-local-hanaccount/api';let setup=false,ready=false,busy=false,controller;
const messages={invalid_password:'密码不正确，请重试。',access_denied:'当前访问被拒绝，请检查访问规则。',proxy_misconfigured:'反向代理配置错误，请联系管理员。',native_bridge_unavailable:'服务器认证暂不可用，请联系管理员。',password_not_configured:'请先在服务器本机设置访问密码。'};
async function request(path,body,signal){const r=await fetch(api+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal,redirect:'error'});const j=await r.json();if(!r.ok)throw Error(j.code==='rate_limited'?'尝试过多，请在 '+(j.retryAfterSec||60)+' 秒后重试。':messages[j.code]||'操作失败，请重试。');return j}
function update(){ $('submit').disabled=!ready||busy||!$('password').value||(setup&&($('password').value.length<8||$('password').value!==$('confirm').value)); }
function mode(passkey){$('passkeyPanel').hidden=!passkey;$('form').hidden=passkey;$('passkeyTab').classList.toggle('active',passkey);$('passwordTab').classList.toggle('active',!passkey)}
async function run(action){if(busy)return;busy=true;controller=new AbortController;const signal=controller.signal;$('error').hidden=true;$('cancel').hidden=false;$('status').textContent='登录中…';$('passkeyButton').disabled=true;update();try{await action(signal);if(!signal.aborted){$('password').value='';$('confirm').value='';location.replace('/')}}catch(e){if(e.name==='AbortError')$('status').textContent='已取消';else{$('error').textContent=e.message;$('error').hidden=false;$('status').textContent=''}}finally{busy=false;controller=null;$('cancel').hidden=true;$('passkeyButton').disabled=false;update()}}
$('cancel').onclick=()=>controller?.abort();$('password').oninput=$('confirm').oninput=update;$('passwordTab').onclick=()=>mode(false);$('passkeyTab').onclick=()=>mode(true);
$('form').onsubmit=e=>{e.preventDefault();if($('submit').disabled)return;run(signal=>request(setup?'/auth/setup':'/auth/login',{password:$('password').value},signal))};
function buffer(value){const text=atob(value.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(text,c=>c.charCodeAt(0)).buffer}
function encoded(value){return btoa(String.fromCharCode(...new Uint8Array(value))).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'')}
$('passkeyButton').onclick=()=>run(async signal=>{const options=await request('/auth/passkey/login/options',{},signal);options.challenge=buffer(options.challenge);options.allowCredentials=(options.allowCredentials||[]).map(c=>({...c,id:buffer(c.id)}));const cred=await navigator.credentials.get({publicKey:options,signal});if(!cred)throw Error('已取消 Passkey 登录');const response=cred.response;await request('/auth/passkey/login/verify',{id:cred.id,rawId:encoded(cred.rawId),type:cred.type,response:{clientDataJSON:encoded(response.clientDataJSON),authenticatorData:encoded(response.authenticatorData),signature:encoded(response.signature),...(response.userHandle?{userHandle:encoded(response.userHandle)}:{})},clientExtensionResults:cred.getClientExtensionResults?.()||{}},signal)});
request('/auth/me').then(me=>{if(me.authenticated&&me.nativeAuthenticated){location.replace('/');return}setup=!me.passwordConfigured;$('title').textContent=setup?'设置访问密码':'登录';$('description').textContent=setup?'首次使用需为本机 DSH 设置访问密码，用于保护 Web 界面与插件 API。':'输入访问密码以继续使用 DSH。';$('confirmField').hidden=$('setupHint').hidden=!setup;$('confirm').required=setup;if(setup){$('password').minLength=8;$('password').autocomplete='new-password';$('password').placeholder='至少 8 位';$('submit').textContent='设置密码并继续';document.querySelector('[data-lha-dialog]').setAttribute('data-lha-setup','')}if(me.ip){$('ip').textContent='当前 IP：'+me.ip+(me.whitelisted?'（白名单）':'');$('ip').hidden=false;$('warning').hidden=!!me.whitelisted}const passkey=me.passkey||{},canPasskey=isSecureContext&&typeof PublicKeyCredential!=='undefined'&&passkey.available;if(!setup&&canPasskey&&passkey.count>0){$('tabs').hidden=false;mode(true)}else if(!canPasskey&&passkey.hint){$('passkeyHint').textContent=passkey.hint;$('passkeyHint').hidden=false}ready=true;$('status').textContent='';update()}).catch(()=>{$('error').textContent='无法检查访问控制，请刷新页面重试。';$('error').hidden=false;$('status').textContent=''});
</script></body></html>`
}
